
name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install
      - run: npm run build

      - name: commit built branch
        run: |
          set +e

          git config user.name github-actions
          git config user.email github-actions@github.com

          cp -R dist /tmp/dist
          git fetch
          git branch -a
          git checkout -f -b built origin/built
          cp -R /tmp/dist/* .
          rm -rf ./node_modules
          git status

          git add .
          git commit -m "built"
          git push

      # - name: deploy
      #   run: |
      #     curl -i \
      #       -X POST \
      #       -H "X-ONSTATIC-KEY: ${{ secrets.ONSTATIC_KEY }}" \
      #       -H "X-ONSTATIC-REPONAME: git@github.com:sters/tools.gomiba.co.git" \
      #       -H "X-ONSTATIC-REPONAME: builtxxxx" \
      #       https://static.gomiba.co/pull
